spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/keystone_db
    username: keystone_user
    password: keystone_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: KeystonePool-Dev
      maximum-pool-size: 5

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    default-schema: public
    schemas: public
    connect-retries: 3

logging:
  level:
    com.keystone: DEBUG
    org.springframework.security: DEBUG
    org.flywaydb: DEBUG